echo -e "\e[1;36m+--------------------------------------------------+\e[0m"
echo -e "\e[1;36m|   Install Bot Manager DigitalOcean By Sanstore   |\e[0m"
echo -e "\e[1;36m+--------------------------------------------------+\e[0m"
read -p "Masukkan Token BOT : "
read -p "Masukkan ChatID : "
